### ISSUE TITLE
PMD Failure: Avoid unused private fields

### ISSUE THREAD

**Issue by rufattabaev** [rufattabaev/Electronic-queue-serice#4]

**Comment by rufattabaev** [comment]
Maven verify выдает следующую ошибку:

PMD Failure: ru.itpark.Person:4 Rule:UnusedPrivateField Priority:3 Avoid unused private fields such as 'name'..

Не могу понять почему. 

Если добавляю геттер в Person для поля name то сборка проходит успешно, но покрытие кода становится меньше 100%.

Что можно сделать?

**Comment by coursar** [comment]
Попробуйте сделать `mvn clean` потом `mvn verify`. По крайней мере в Travis с get/set всё ок.

Не забудьте сделать `git pull`.

**Comment by rufattabaev** [comment]
Я пробовал делать mvn clean. Результат такой же.
